repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: "3.10"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
